In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("05AdventureWorks Returns Data.csv", encoding="latin1")

In [5]:
df

     ReturnDate  TerritoryKey  ProductKey  ReturnQuantity
0     1/18/2020             9         312               1
1     1/18/2020            10         310               1
2     1/21/2020             8         346               1
3     1/22/2020             4         311               1
4      2/2/2020             6         312               1
...         ...           ...         ...             ...
1804  6/30/2022             6         491               1
1805  6/30/2022             8         477               1
1806  6/30/2022             9         477               1
1807  6/30/2022            10         223               1
1808  6/30/2022            10         477               1

[1809 rows x 4 columns]

In [6]:
df["ReturnDate"] = pd.to_datetime(
    df["ReturnDate"]
)

df["DateKey"] = df["ReturnDate"].dt.strftime("%Y%m%d")

In [7]:
df

     ReturnDate  TerritoryKey  ProductKey  ReturnQuantity   DateKey
0    2020-01-18             9         312               1  20200118
1    2020-01-18            10         310               1  20200118
2    2020-01-21             8         346               1  20200121
3    2020-01-22             4         311               1  20200122
4    2020-02-02             6         312               1  20200202
...         ...           ...         ...             ...       ...
1804 2022-06-30             6         491               1  20220630
1805 2022-06-30             8         477               1  20220630
1806 2022-06-30             9         477               1  20220630
1807 2022-06-30            10         223               1  20220630
1808 2022-06-30            10         477               1  20220630

[1809 rows x 5 columns]

In [8]:
df.to_excel("05AdventureWorks Returns Data.xlsx", index=False)